### ISSUE TITLE
Package imports numpy in setup.py, leads to installation disasters

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/stsci.imagestats#19]
If you attempt to install this package in a clean environment, it will fail since `numpy` is being imported in the `setup.py` script.

This is especially problematic since it is a dependency of the JWST pipeline, which means it is not possible to install the pipeline in a clean environment without installing `numpy` first.

This project should include a `pyproject.toml` file with the proper build-time dependencies (namely, `numpy`). See [PEP 518](https://www.python.org/dev/peps/pep-0518/) for more information, and the `pyproject.toml` file [in scipy](https://github.com/scipy/scipy/blob/master/pyproject.toml) for an example.

**Comment by jdavies-st** [comment]
@jhunkeler 👋

**Comment by mcara** [comment]
> This project should include a pyproject.toml file with the proper build-time dependencies (namely, numpy). See PEP 518 for more information, and the pyproject.toml file in scipy for an example.

Doesn't it already includes https://github.com/spacetelescope/stsci.imagestats/blob/master/pyproject.toml ?

**Comment by jhunkeler** [comment]
```
$ python -m venv ~/local/venv/hmm                                   
$ source ~/local/venv/hmm/bin/activate                              
(hmm) $ pip install stsci.imagestats                                
Collecting stsci.imagestats
  Downloading https://files.pythonhosted.org/packages/de/1b/38d13e276a7a71dd2602d0fcedb5e8bc554fa7c908fafb54909f3a652b9d/stsci.imagestats-1.6.1.tar.gz (96kB)
    100% |████████████████████████████████| 102kB 5.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zielw0d5/stsci.imagestats/setup.py", line 2, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
```

Robust.

**Comment by jhunkeler** [comment]
```
(hmm) $ git clone https://github.com/spacetelescope/stsci.imagestats && cd stsci.imagestats
(hmm) stsci.imagestats $ pip install -e .
Obtaining file:///home/jhunk/Downloads/stsci.imagestats
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.13 (from stsci.imagestats==1.6.1)
  Using cached https://files.pythonhosted.org/packages/91/e7/6c780e612d245cca62bc3ba8e263038f7c144a96a54f877f3714a0e8427e/numpy-1.16.2-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: numpy, stsci.imagestats
  Running setup.py develop for stsci.imagestats
Successfully installed numpy-1.16.2 stsci.imagestats
```
Ok, so probably means `pyproject.toml` isn't getting included in the `MANIFEST`. :angry:

**Comment by mcara** [comment]
What kind of environment name is `(hmm)`?

**Comment by jhunkeler** [comment]
@drdavella The pypi index might need a few minutes to settle but 1.6.2 is now "live".

**Comment by jdavies-st** [comment]
Tested it, and it works great.  Thanks @jhunkeler!
