### ISSUE TITLE
BLD: Use OpenAstronomy publish workflow, provide a lot of wheels

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.imagestats#39]
Since you have C-extension, you need to generate a wheel for different distribution combos. The spacetelescope workflow is very limited. I propose you switch to OpenAstronomy instead.

https://github.com/OpenAstronomy/github-actions-workflows#build-and-publish-a-python-package

Example usage in production: https://github.com/astropy/astropy/blob/main/.github/workflows/publish.yml

**Comment by mcara** [comment]
@zacharyburnett Could you, please look into this? Thanks!
